BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "regions" (
	"id"	INTEGER,
	"name"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "personae" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"person_id"	INTEGER NOT NULL,
	"official"	INTEGER NOT NULL CHECK("official" IN (0, 1)),
	"search_name"	TEXT,
	FOREIGN KEY("person_id") REFERENCES "people"("id"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "groups" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "award_types" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"precedence"	INTEGER NOT NULL,
	"group_id"	INTEGER NOT NULL,
	"open"	INTEGER CHECK("open" IN (0, 1, NULL)),
	FOREIGN KEY("group_id") REFERENCES "groups"("id"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "crowns" (
	"id"	INTEGER,
	"name"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "reigns" (
	"id"	INTEGER,
	"sov1"	TEXT,
	"sov2"	TEXT,
	"begin"	TEXT,
	"end"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "scribes" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"description"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "scroll_status" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "events" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"slug"	TEXT,
	"provenance"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "awards" (
	"id"	INTEGER,
	"type_id"	INTEGER NOT NULL,
	"persona_id"	INTEGER NOT NULL,
	"crown_id"	INTEGER,
	"event_id"	INTEGER,
	"date"	TEXT,
	"scribe_id"	INTEGER,
	"scroll_status_id"	INTEGER,
	"scroll_updated"	TEXT,
	"scroll_comment"	TEXT,
	"provenance"	INTEGER,
	FOREIGN KEY("scribe_id") REFERENCES "scribes"("id"),
	FOREIGN KEY("type_id") REFERENCES "award_types"("id"),
	FOREIGN KEY("crown_id") REFERENCES "crowns"("id"),
	FOREIGN KEY("event_id") REFERENCES "events"("id"),
	FOREIGN KEY("scroll_status_id") REFERENCES "scroll_status"("id"),
	FOREIGN KEY("persona_id") REFERENCES "personae"("id"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "people" (
	"id"	INTEGER,
	"surname"	TEXT,
	"forename"	TEXT,
	"region_id"	INTEGER NOT NULL,
	"blazon"	TEXT,
	"emblazon"	TEXT,
	"notes"	TEXT,
	FOREIGN KEY("region_id") REFERENCES "regions"("id"),
	PRIMARY KEY("id")
);
INSERT INTO "regions" VALUES (1,NULL);
INSERT INTO "regions" VALUES (2,'Insulae Draconis');
INSERT INTO "regions" VALUES (3,'Nordmark');
INSERT INTO "regions" VALUES (4,'Aarnimetsä');
INSERT INTO "regions" VALUES (5,'Central Region');
INSERT INTO "regions" VALUES (6,'Drachenwald');
INSERT INTO "regions" VALUES (7,'Elsewhere');
INSERT INTO "personae" VALUES (1545,'John The Green',1557,1,'');
INSERT INTO "personae" VALUES (2418,'íone',2489,1,'ione ionne');
INSERT INTO "personae" VALUES (3623,'Thomas',3226,1,'');
INSERT INTO "personae" VALUES (3624,'Sara of Nordmark',3227,1,'');
INSERT INTO "personae" VALUES (3625,'Yda',3228,1,'');
INSERT INTO "personae" VALUES (3626,'Anna S. Þorvaldsdóttir',3229,1,'Anna S. Thorvaldsdóttir  Anna S. Thorvaldsdottir');
INSERT INTO "personae" VALUES (3627,'Tiffany',3230,1,'');
INSERT INTO "personae" VALUES (3628,'Seamus',3231,1,'');
INSERT INTO "personae" VALUES (3629,'Sven The Red',3232,1,'');
INSERT INTO "personae" VALUES (3630,'Hildegard',3233,1,'');
INSERT INTO "personae" VALUES (3631,'James',3234,1,'');
INSERT INTO "personae" VALUES (3632,'Eduard',3235,1,'Edward');
INSERT INTO "personae" VALUES (3633,'Einli',3236,1,'');
INSERT INTO "personae" VALUES (3634,'Florence',3237,1,'');
INSERT INTO "groups" VALUES (1,'SCA');
INSERT INTO "groups" VALUES (2,'Drachenwald');
INSERT INTO "groups" VALUES (3,'Nordmark');
INSERT INTO "groups" VALUES (4,'Aarnimetsä');
INSERT INTO "groups" VALUES (5,'Knight''s Crossing');
INSERT INTO "groups" VALUES (6,'Æthelmearc');
INSERT INTO "groups" VALUES (7,'An Tir');
INSERT INTO "groups" VALUES (8,'Ansteorra');
INSERT INTO "groups" VALUES (9,'Artemesia');
INSERT INTO "groups" VALUES (10,'Atenveldt');
INSERT INTO "groups" VALUES (11,'Atlantia');
INSERT INTO "groups" VALUES (12,'Caid');
INSERT INTO "groups" VALUES (13,'Calontir');
INSERT INTO "groups" VALUES (14,'Cynagua');
INSERT INTO "groups" VALUES (15,'Ealdormere');
INSERT INTO "groups" VALUES (16,'East');
INSERT INTO "groups" VALUES (17,'Lochac');
INSERT INTO "groups" VALUES (18,'Meridies');
INSERT INTO "groups" VALUES (19,'Middle');
INSERT INTO "groups" VALUES (20,'Mists');
INSERT INTO "groups" VALUES (21,'Oertha');
INSERT INTO "groups" VALUES (22,'Outlands');
INSERT INTO "groups" VALUES (23,'Trimaris');
INSERT INTO "groups" VALUES (24,'West');
INSERT INTO "groups" VALUES (25,'Styringheim');
INSERT INTO "groups" VALUES (26,'Northshield');
INSERT INTO "groups" VALUES (27,'Insulae Draconis');
INSERT INTO "groups" VALUES (28,'Gleann Abhann');
INSERT INTO "groups" VALUES (29,'Drei Eichen');
INSERT INTO "groups" VALUES (30,'Gotvik');
INSERT INTO "groups" VALUES (31,'Tir Righ');
INSERT INTO "groups" VALUES (32,'Avacal');
INSERT INTO "groups" VALUES (33,'Ponte Alto');
INSERT INTO "groups" VALUES (34,'unknown');
INSERT INTO "groups" VALUES (35,'An Crosaire');
INSERT INTO "groups" VALUES (36,'Darkwater');
INSERT INTO "groups" VALUES (37,'Windmaster''s Hill');
INSERT INTO "groups" VALUES (38,'Ile du Dragon Dormant');
INSERT INTO "groups" VALUES (39,'Glymm Mere');
INSERT INTO "groups" VALUES (40,'Red Spears');
INSERT INTO "groups" VALUES (41,'Stierbach');
INSERT INTO "groups" VALUES (42,'Eplaheimr');
INSERT INTO "groups" VALUES (43,'Far West');
INSERT INTO "award_types" VALUES (1,'Award of Arms',200,1,1);
INSERT INTO "award_types" VALUES (2,'Popular Company of Sojourners (PCS)',100,2,1);
INSERT INTO "award_types" VALUES (3,'Panache, Order of the',300,2,1);
INSERT INTO "award_types" VALUES (4,'Lindquistringes, Orden des',300,2,1);
INSERT INTO "award_types" VALUES (5,'Silver Guard, Order of the',300,2,1);
INSERT INTO "award_types" VALUES (6,'Gyllene Bandets Orden (Golden Ribbon)',300,3,1);
INSERT INTO "award_types" VALUES (7,'LjusOrden (Light)',300,3,NULL);
INSERT INTO "award_types" VALUES (8,'Vita portens Väktare (White Portal)',300,3,NULL);
INSERT INTO "award_types" VALUES (9,'Courtesy, Queen''s Order of',100,2,1);
INSERT INTO "award_types" VALUES (10,'Court Barony',600,1,1);
INSERT INTO "award_types" VALUES (11,'Grant of Arms',400,1,1);
INSERT INTO "award_types" VALUES (12,'Knighthood',700,1,1);
INSERT INTO "award_types" VALUES (13,'Mastery of Arms',700,1,1);
INSERT INTO "award_types" VALUES (14,'Laurel, Order of the',700,1,1);
INSERT INTO "award_types" VALUES (15,'Pelican, Order of the',700,1,1);
INSERT INTO "award_types" VALUES (16,'Patent of Arms',700,1,1);
INSERT INTO "award_types" VALUES (17,'Dragon''s Tear, Award of the',100,2,1);
INSERT INTO "award_types" VALUES (18,'Dragon''s Bowle, Order of the',100,2,1);
INSERT INTO "award_types" VALUES (19,'Dragon''s Jewel, Order of the',100,2,1);
INSERT INTO "award_types" VALUES (20,'Dragon''s Pride, Order of the',100,2,1);
INSERT INTO "award_types" VALUES (21,'Dragon''s Steel, Order of the',500,2,0);
INSERT INTO "award_types" VALUES (22,'Sigillum Coronae - King',100,2,1);
INSERT INTO "award_types" VALUES (23,'Sigillum Coronae - King and Queen',100,2,1);
INSERT INTO "award_types" VALUES (24,'Sigillum Coronae - Queen',100,2,1);
INSERT INTO "award_types" VALUES (25,'Albion, King''s Order of the Companions of',100,2,1);
INSERT INTO "award_types" VALUES (26,'Hospitallers of Albion',100,2,1);
INSERT INTO "award_types" VALUES (27,'Rose, Order of the',100,1,1);
INSERT INTO "award_types" VALUES (28,'County',900,1,1);
INSERT INTO "award_types" VALUES (29,'Viscounty',800,1,1);
INSERT INTO "award_types" VALUES (30,'Duchy',1000,1,1);
INSERT INTO "award_types" VALUES (31,'Augmentation of Arms',100,1,1);
INSERT INTO "award_types" VALUES (32,'Carneol of Nordmark',100,3,NULL);
INSERT INTO "award_types" VALUES (33,'Salladins Ring',100,3,NULL);
INSERT INTO "award_types" VALUES (34,'Nordmark Malachite',100,3,NULL);
INSERT INTO "award_types" VALUES (35,'Hopeisen solmun ritarikunta',100,4,1);
INSERT INTO "award_types" VALUES (36,'Kultainen mehiläinen (Golden Bee)',100,4,1);
INSERT INTO "award_types" VALUES (37,'Rautahirven ritarikunta',100,4,1);
INSERT INTO "award_types" VALUES (38,'Katkennut kynä (Broken Pen)',100,4,1);
INSERT INTO "award_types" VALUES (39,'Harmaa virvaliekki (Grey)',100,4,1);
INSERT INTO "award_types" VALUES (40,'Keltainen virvaliekki (Yellow)',100,4,1);
INSERT INTO "award_types" VALUES (41,'Musta virvaliekki (Black)',100,4,1);
INSERT INTO "award_types" VALUES (42,'Punainen virvaliekki (Red)',100,4,1);
INSERT INTO "award_types" VALUES (43,'Purppura virvaliekki (Purple)',100,4,1);
INSERT INTO "award_types" VALUES (44,'Sininen virvaliekki (Blue)',100,4,1);
INSERT INTO "award_types" VALUES (45,'Valkoinen virvaliekki (White)',100,4,1);
INSERT INTO "award_types" VALUES (46,'Vihreä virvaliekki (Green)',100,4,1);
INSERT INTO "award_types" VALUES (47,'Wheel, Order of the',100,5,1);
INSERT INTO "award_types" VALUES (48,'Albion, Prince''s Order of the Companions of',100,2,0);
INSERT INTO "award_types" VALUES (49,'Black Dragon''s Garter',100,2,0);
INSERT INTO "award_types" VALUES (50,'Courtesy, Princess'' Order of',100,2,0);
INSERT INTO "award_types" VALUES (51,'Sigillum Principae',100,2,0);
INSERT INTO "award_types" VALUES (52,'Sigillum Principessa',100,2,0);
INSERT INTO "award_types" VALUES (53,'Edelweiss (formerly Marguerite), Order of the',300,2,0);
INSERT INTO "award_types" VALUES (54,'Marguerite, Order of the',300,2,0);
INSERT INTO "award_types" VALUES (55,'Aster Mortis',100,3,0);
INSERT INTO "award_types" VALUES (56,'Drömmens Orden',300,3,0);
INSERT INTO "award_types" VALUES (57,'Fleur of Æthelmearc, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (58,'Gage, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (59,'Golden Alce, Order of the',300,6,NULL);
INSERT INTO "award_types" VALUES (60,'Keystone, Order of the',300,6,NULL);
INSERT INTO "award_types" VALUES (61,'Millrind, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (62,'Scarlet Guard, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (63,'Sycamore, Order of the',300,6,NULL);
INSERT INTO "award_types" VALUES (64,'White Scarf, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (65,'White Horn, Order of the',500,6,NULL);
INSERT INTO "award_types" VALUES (66,'Grey Goose Shaft',500,7,NULL);
INSERT INTO "award_types" VALUES (67,'Goutte de Sang, Order of the',500,7,NULL);
INSERT INTO "award_types" VALUES (68,'Hasta Leonis',500,7,NULL);
INSERT INTO "award_types" VALUES (69,'Jambe de Lion, Order of the',500,7,NULL);
INSERT INTO "award_types" VALUES (70,'White Scarf, Order of the',500,7,NULL);
INSERT INTO "award_types" VALUES (71,'Centurions of the Sable Star',500,8,NULL);
INSERT INTO "award_types" VALUES (72,'Compass Rose',300,8,NULL);
INSERT INTO "award_types" VALUES (73,'Iris of Merit, Order of the',500,8,'');
INSERT INTO "award_types" VALUES (74,'Kings Gauntlet',300,8,NULL);
INSERT INTO "award_types" VALUES (75,'Queens Glove',300,8,NULL);
INSERT INTO "award_types" VALUES (76,'Sable Comet',300,8,NULL);
INSERT INTO "award_types" VALUES (77,'Sable Crane',300,8,NULL);
INSERT INTO "award_types" VALUES (78,'Sable Thistle, Award of the',300,8,'');
INSERT INTO "award_types" VALUES (79,'Star of Merit',500,8,NULL);
INSERT INTO "award_types" VALUES (80,'White Scarf',500,8,NULL);
INSERT INTO "award_types" VALUES (81,'Cheval d''Or',300,9,NULL);
INSERT INTO "award_types" VALUES (82,'Defenders of the Citadel',500,9,NULL);
INSERT INTO "award_types" VALUES (83,'Golden Feather of Artemesia',300,9,0);
INSERT INTO "award_types" VALUES (84,'Golden Maple Leaf',300,9,NULL);
INSERT INTO "award_types" VALUES (85,'Golden Pillar, Order of the',300,9,NULL);
INSERT INTO "award_types" VALUES (86,'Golden Scarf',300,9,NULL);
INSERT INTO "award_types" VALUES (87,'Golden Sun in Splendour',500,9,NULL);
INSERT INTO "award_types" VALUES (88,'Gryphon and Pheon, Order of the',300,9,NULL);
INSERT INTO "award_types" VALUES (89,'Gryphon of Artemesia',500,9,NULL);
INSERT INTO "award_types" VALUES (90,'Gryphon''s Eye',300,9,NULL);
INSERT INTO "award_types" VALUES (91,'Gryphon''s Pheon of Artemesia',300,9,0);
INSERT INTO "award_types" VALUES (92,'Gryphon''s Talon of Artemesia',300,9,NULL);
INSERT INTO "award_types" VALUES (93,'Key Cross',500,9,NULL);
INSERT INTO "award_types" VALUES (94,'Maple Leaf of Artemesia',300,9,0);
INSERT INTO "award_types" VALUES (95,'Pillar of Artemesia',300,9,0);
INSERT INTO "award_types" VALUES (96,'White Scarf of Artemesia',500,9,NULL);
INSERT INTO "award_types" VALUES (97,'Azure Archer',300,10,NULL);
INSERT INTO "award_types" VALUES (98,'Builders of Atenveldt',100,10,NULL);
INSERT INTO "award_types" VALUES (99,'Commanders of the Light of Atenveldt',500,10,NULL);
INSERT INTO "award_types" VALUES (100,'Commanders of the Fleur de Soleil',500,10,NULL);
INSERT INTO "award_types" VALUES (101,'Commanders of the Hawks Lure',500,10,NULL);
INSERT INTO "award_types" VALUES (102,'Commanders of the Azure Archers',500,10,NULL);
INSERT INTO "award_types" VALUES (103,'Commanders of the Queen''s Grace',500,10,NULL);
INSERT INTO "award_types" VALUES (104,'Defenders of the White Scarf (DWS)',500,10,NULL);
INSERT INTO "award_types" VALUES (105,'Fleur de Soleil',300,10,NULL);
INSERT INTO "award_types" VALUES (106,'Guardians of Atenveldt',300,10,NULL);
INSERT INTO "award_types" VALUES (107,'Hawks Lure',300,10,NULL);
INSERT INTO "award_types" VALUES (108,'La Orden Del Sirviente Del Sol',300,10,NULL);
INSERT INTO "award_types" VALUES (109,'Le Orden De La Luz De La Estrellas',300,10,NULL);
INSERT INTO "award_types" VALUES (110,'Le Ordre Le Artisan De Soleil',300,10,NULL);
INSERT INTO "award_types" VALUES (111,'Light of Atenveldt',300,10,NULL);
INSERT INTO "award_types" VALUES (112,'Lion of Atenveldt',500,10,NULL);
INSERT INTO "award_types" VALUES (113,'Blood of Fenris, Order of the',300,10,NULL);
INSERT INTO "award_types" VALUES (114,'Sable Pheon, Order of the',300,10,NULL);
INSERT INTO "award_types" VALUES (115,'Sword of the Rose, Order of the',300,10,NULL);
INSERT INTO "award_types" VALUES (116,'Queens Grace',100,10,NULL);
INSERT INTO "award_types" VALUES (117,'Academie d''Espee',500,11,0);
INSERT INTO "award_types" VALUES (118,'Golden Dolphin, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (119,'Non Pareil, Order of the',100,11,NULL);
INSERT INTO "award_types" VALUES (120,'Pearl, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (121,'Sea Stag, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (122,'Yew Bow, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (123,'Queen''s Order of Courtesy',100,11,NULL);
INSERT INTO "award_types" VALUES (124,'White Scarf, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (125,'Kraken, Order of the',500,11,NULL);
INSERT INTO "award_types" VALUES (126,'Opal, Order of the',300,11,NULL);
INSERT INTO "award_types" VALUES (127,'Silver Osprey, Order of the',300,11,NULL);
INSERT INTO "award_types" VALUES (128,'Coral Branch, Order of the',300,11,1);
INSERT INTO "award_types" VALUES (129,'King''s Missiliers, Order of the',300,11,NULL);
INSERT INTO "award_types" VALUES (130,'Order of Chiron',500,12,NULL);
INSERT INTO "award_types" VALUES (131,'Argent Arrow, Order of the',300,12,NULL);
INSERT INTO "award_types" VALUES (132,'Crescent, Order of the',500,12,NULL);
INSERT INTO "award_types" VALUES (133,'Crescent Sword, Order of the',300,12,NULL);
INSERT INTO "award_types" VALUES (134,'Dolphin of Caid, Order of the',300,12,NULL);
INSERT INTO "award_types" VALUES (135,'Duellist, Order of the',300,12,NULL);
INSERT INTO "award_types" VALUES (136,'Gauntlet, Order of the',500,12,NULL);
INSERT INTO "award_types" VALUES (137,'Harp Argent, Order of the',300,12,NULL);
INSERT INTO "award_types" VALUES (138,'Lux Caidus, Order of the',500,12,NULL);
INSERT INTO "award_types" VALUES (139,'White Scarf of Caid, Order of the',500,12,NULL);
INSERT INTO "award_types" VALUES (140,'Boga-Fyrd',300,13,NULL);
INSERT INTO "award_types" VALUES (141,'Boga-Hirth',500,13,NULL);
INSERT INTO "award_types" VALUES (142,'Iren-Fyrd',300,13,NULL);
INSERT INTO "award_types" VALUES (143,'Iren-Hirth',500,13,NULL);
INSERT INTO "award_types" VALUES (144,'Calon Lily, Order of the',500,13,NULL);
INSERT INTO "award_types" VALUES (145,'Cross of Calontir, Order of the',500,13,NULL);
INSERT INTO "award_types" VALUES (146,'Golden Calon Swan, Order of the',300,13,NULL);
INSERT INTO "award_types" VALUES (147,'Leather Mallet, Order of the',300,13,NULL);
INSERT INTO "award_types" VALUES (148,'Silver Hammer, Order of the',500,13,NULL);
INSERT INTO "award_types" VALUES (149,'Torse, Order of the',300,13,NULL);
INSERT INTO "award_types" VALUES (150,'Crystal Swan, Order of the',100,14,NULL);
INSERT INTO "award_types" VALUES (151,'Ruxton',300,14,NULL);
INSERT INTO "award_types" VALUES (152,'Maiden''s Heart',300,15,NULL);
INSERT INTO "award_types" VALUES (153,'Crucible, Order of the',500,15,NULL);
INSERT INTO "award_types" VALUES (154,'Wain, Order of the',500,15,NULL);
INSERT INTO "award_types" VALUES (155,'Order of Thorbjorn''s Hammer',500,15,NULL);
INSERT INTO "award_types" VALUES (156,'Orion',300,15,NULL);
INSERT INTO "award_types" VALUES (157,'Scarlet Banner',300,15,NULL);
INSERT INTO "award_types" VALUES (158,'Golden Rapier, Order of the',300,16,NULL);
INSERT INTO "award_types" VALUES (159,'Maunche, Order of the',300,16,NULL);
INSERT INTO "award_types" VALUES (160,'Sagittarius, Order of the',300,16,NULL);
INSERT INTO "award_types" VALUES (161,'Silver Crescent, Order of the',300,16,NULL);
INSERT INTO "award_types" VALUES (162,'Tygers Combattant, Order of the',300,16,NULL);
INSERT INTO "award_types" VALUES (163,'Queen''s Order of Courtesy',100,16,NULL);
INSERT INTO "award_types" VALUES (164,'Company of Archers',500,17,NULL);
INSERT INTO "award_types" VALUES (165,'Golden Tear, Order of the',300,17,NULL);
INSERT INTO "award_types" VALUES (166,'Lily, Order of the',300,17,NULL);
INSERT INTO "award_types" VALUES (167,'White Scarf of Lochac, Order of the',500,17,NULL);
INSERT INTO "award_types" VALUES (168,'Argent Comet, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (169,'Bough, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (170,'Sable Sword, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (171,'Scarlet Star, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (172,'Velvet Owl, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (173,'Legio Ursi, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (174,'Split Arrow, Order of the',300,18,NULL);
INSERT INTO "award_types" VALUES (175,'Bronze Ring, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (176,'Cavendish Knot, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (177,'Doe''s Grace, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (178,'Dragon''s Barb, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (179,'Dragon''s Heart, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (180,'Dragon''s Tooth, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (181,'Evergreen, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (182,'Gaping Wound, Order of the',300,19,0);
INSERT INTO "award_types" VALUES (183,'Gold Mace, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (184,'Greenwood Company, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (185,'King''s Chalice, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (186,'Purple Fret, Award of the',300,19,NULL);
INSERT INTO "award_types" VALUES (187,'Queen''s Favor, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (188,'Red Company, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (189,'Silver Oak, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (190,'White Chamfron, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (191,'White Lance, Order of the',500,19,NULL);
INSERT INTO "award_types" VALUES (192,'Willow, Order of the',300,19,NULL);
INSERT INTO "award_types" VALUES (193,'Dames de la Mer, Order of the',100,20,NULL);
INSERT INTO "award_types" VALUES (194,'Holders of the Heart',100,21,NULL);
INSERT INTO "award_types" VALUES (195,'Order of Sharparrow',500,22,NULL);
INSERT INTO "award_types" VALUES (196,'Argent Hart, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (197,'Flower, Order of the',500,22,NULL);
INSERT INTO "award_types" VALUES (198,'Golden Pheon, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (199,'Iron Hart, Order of the',500,22,NULL);
INSERT INTO "award_types" VALUES (200,'Sharparrow, Order of the',500,22,NULL);
INSERT INTO "award_types" VALUES (201,'Silver Stirrup, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (202,'Silver Tyne, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (203,'Stag, Order of the',500,22,NULL);
INSERT INTO "award_types" VALUES (204,'Stag''s Blood, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (205,'Stag''s Heart, Order of the',300,22,NULL);
INSERT INTO "award_types" VALUES (206,'White Scarf, Order of the',500,22,NULL);
INSERT INTO "award_types" VALUES (207,'Arc d''Or, Order of the',500,23,NULL);
INSERT INTO "award_types" VALUES (208,'Argent Scales of Trimaris, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (209,'Argent Sword of Trimaris, Order of the',500,23,NULL);
INSERT INTO "award_types" VALUES (210,'Cross and Serpent, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (211,'Silver Shield of Trimaris, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (212,'Silver Trident Trimaris, Order of the',500,23,NULL);
INSERT INTO "award_types" VALUES (213,'Trade Winds of Trimaris, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (214,'Trident Keype, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (215,'Triskele Trimaris, Order of the',500,23,NULL);
INSERT INTO "award_types" VALUES (216,'White Scarf of Trimaris, Order of the',500,23,NULL);
INSERT INTO "award_types" VALUES (217,'Wyvern''s Claw, Order of the',300,23,NULL);
INSERT INTO "award_types" VALUES (218,'Guildmasters of Fence',500,24,NULL);
INSERT INTO "award_types" VALUES (219,'Leaf of Merit, Order of the',300,24,NULL);
INSERT INTO "award_types" VALUES (220,'Rose Leaf, Order of the',300,24,NULL);
INSERT INTO "award_types" VALUES (221,'Western Lily, Order of the',300,24,NULL);
INSERT INTO "award_types" VALUES (222,'Queen''s Order of Grace',100,24,NULL);
INSERT INTO "award_types" VALUES (223,'Royal Company of Archers',500,24,NULL);
INSERT INTO "award_types" VALUES (224,'Royal Company of Yeomen',500,24,NULL);
INSERT INTO "award_types" VALUES (225,'Galt',100,25,1);
INSERT INTO "award_types" VALUES (226,'Havdes Följe',100,25,1);
INSERT INTO "award_types" VALUES (227,'Örn',100,25,1);
INSERT INTO "award_types" VALUES (228,'Orm',100,25,1);
INSERT INTO "award_types" VALUES (229,'Bysen',100,25,1);
INSERT INTO "award_types" VALUES (230,'Torspeisku',100,25,1);
INSERT INTO "award_types" VALUES (231,'Di sma undar jårdi',100,25,1);
INSERT INTO "award_types" VALUES (232,'Queen''s Cypher',100,16,1);
INSERT INTO "award_types" VALUES (233,'King''s Cypher',100,16,1);
INSERT INTO "award_types" VALUES (234,'Hasta Belli, Order of the',300,17,1);
INSERT INTO "award_types" VALUES (235,'Nock, Order of the',300,17,1);
INSERT INTO "award_types" VALUES (237,'Order of Grace',100,17,1);
INSERT INTO "award_types" VALUES (238,'Order of the Burning Trumpet',100,18,1);
INSERT INTO "award_types" VALUES (239,'Fanged Wolf',300,10,1);
INSERT INTO "award_types" VALUES (240,'Queen''s Cypher, Order of the',100,10,1);
INSERT INTO "award_types" VALUES (241,'Sea Dragon, Order of the',300,11,1);
INSERT INTO "award_types" VALUES (242,'Tyr, Order of',500,26,1);
INSERT INTO "award_types" VALUES (243,'Destrer, Order of the',500,26,1);
INSERT INTO "award_types" VALUES (244,'Iron Griffin Legion',500,26,1);
INSERT INTO "award_types" VALUES (245,'White Scarf, Order of the',500,26,1);
INSERT INTO "award_types" VALUES (246,'Aquila, Order of',500,26,1);
INSERT INTO "award_types" VALUES (247,'Order of Bridget''s Flame',500,26,1);
INSERT INTO "award_types" VALUES (248,'Order of the Queen''s Cypher',100,10,1);
INSERT INTO "award_types" VALUES (249,'Sable Falcon',300,8,1);
INSERT INTO "award_types" VALUES (250,'Order of the Aspen of Caerthe',100,22,1);
INSERT INTO "award_types" VALUES (251,'Troubadours, Order of the',100,16,1);
INSERT INTO "award_types" VALUES (252,'Styråran',100,25,1);
INSERT INTO "award_types" VALUES (253,'Prince''s Cypher',100,17,1);
INSERT INTO "award_types" VALUES (254,'Silver Tear',100,17,1);
INSERT INTO "award_types" VALUES (255,'Golden Tear',300,17,1);
INSERT INTO "award_types" VALUES (256,'Legion of Courtesy',100,12,1);
INSERT INTO "award_types" VALUES (257,'Golden Lilly',300,17,1);
INSERT INTO "award_types" VALUES (258,'Queen''s Cypher',100,24,1);
INSERT INTO "award_types" VALUES (259,'Styraran',100,25,1);
INSERT INTO "award_types" VALUES (260,'Ffraid, Order of',100,27,1);
INSERT INTO "award_types" VALUES (261,'Order of the Salamander Barony of Bhakail',100,16,1);
INSERT INTO "award_types" VALUES (262,'Sun and Chalice, Order of the',100,27,1);
INSERT INTO "award_types" VALUES (263,'Fox, Order of the',100,27,1);
INSERT INTO "award_types" VALUES (264,'Silver Martlet, Order of the',100,27,1);
INSERT INTO "award_types" VALUES (265,'Nordmarks Sparre',100,3,1);
INSERT INTO "award_types" VALUES (266,'Citizen of Gleann Abhann',100,28,1);
INSERT INTO "award_types" VALUES (267,'Order of Three Rivers Gold',100,13,1);
INSERT INTO "award_types" VALUES (268,'Sword of Calontir',100,13,1);
INSERT INTO "award_types" VALUES (269,'Queen''s Endorsement of Distinction',100,13,1);
INSERT INTO "award_types" VALUES (270,'Thegn of Calontir',100,13,1);
INSERT INTO "award_types" VALUES (271,'Knight Bannerette',100,24,1);
INSERT INTO "award_types" VALUES (272,'Defender of the West',100,24,1);
INSERT INTO "award_types" VALUES (273,'West Kingdom Paragon of Merriment',100,24,1);
INSERT INTO "award_types" VALUES (274,'Commendabilis',100,24,1);
INSERT INTO "award_types" VALUES (275,'Muckin'' Great Clubbe',100,24,1);
INSERT INTO "award_types" VALUES (276,'Meridian Cross',100,18,1);
INSERT INTO "award_types" VALUES (277,'Argent Shield',100,18,1);
INSERT INTO "award_types" VALUES (278,'Compostella Pilgrims Order',100,18,1);
INSERT INTO "award_types" VALUES (279,'Forget-me-not',100,7,1);
INSERT INTO "award_types" VALUES (280,'Muckin'' Tall Maul',100,7,1);
INSERT INTO "award_types" VALUES (281,'Silver Rose',100,7,1);
INSERT INTO "award_types" VALUES (282,'Spear - Principality of Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (283,'Princess Talon of Favour - Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (284,'Hafoc - Principality of Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (285,'Guardian of Tir Righ - Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (286,'Valorous Estate - Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (287,'L''Etoile d''Argent - Tir Righ',100,7,1);
INSERT INTO "award_types" VALUES (288,'Tir Righ Arts and Science Champion',100,7,1);
INSERT INTO "award_types" VALUES (289,'Lion''s Claw - Barony of Lions Gate',100,7,1);
INSERT INTO "award_types" VALUES (290,'Pied d''Argent',100,24,1);
INSERT INTO "award_types" VALUES (291,'Queen''s Treasure',100,24,1);
INSERT INTO "award_types" VALUES (292,'Roman Lilies',100,17,1);
INSERT INTO "award_types" VALUES (293,'Rose Leaf',100,24,1);
INSERT INTO "award_types" VALUES (294,'Rowan',100,17,1);
INSERT INTO "award_types" VALUES (295,'Princess'' Cypher',100,17,1);
INSERT INTO "award_types" VALUES (296,'Royal Cypher',100,17,1);
INSERT INTO "award_types" VALUES (297,'Order of the Cross of Lochac',100,17,NULL);
INSERT INTO "award_types" VALUES (298,'Ordo Honestus',100,29,NULL);
INSERT INTO "award_types" VALUES (299,'Nordmarks Ekorre',100,3,'');
INSERT INTO "award_types" VALUES (300,'Weissdorne, Orden der',100,5,0);
INSERT INTO "award_types" VALUES (301,'Robin, Order of',100,27,1);
INSERT INTO "award_types" VALUES (303,'Orden der Lindenblüte',100,5,0);
INSERT INTO "award_types" VALUES (304,'King''s Cypher',100,17,NULL);
INSERT INTO "award_types" VALUES (305,'Scroll of Honor',100,15,NULL);
INSERT INTO "award_types" VALUES (306,'Queen''s Cypher',100,22,NULL);
INSERT INTO "award_types" VALUES (307,'Legion of Gallantry of the Outlands',100,22,NULL);
INSERT INTO "award_types" VALUES (308,'Cordon Royal',100,22,NULL);
INSERT INTO "award_types" VALUES (309,'Sable Talon',300,8,NULL);
INSERT INTO "award_types" VALUES (310,'Heliotrope (Barony of Nordskogen)',100,26,NULL);
INSERT INTO "award_types" VALUES (311,'Walker of the Way',100,22,NULL);
INSERT INTO "award_types" VALUES (312,'Order of the Royal Vanguard',100,19,NULL);
INSERT INTO "award_types" VALUES (313,'King''s Favor',100,7,NULL);
INSERT INTO "award_types" VALUES (314,'Winged Pouch, Order of the',100,27,1);
INSERT INTO "award_types" VALUES (315,'Iren Feran',100,13,NULL);
INSERT INTO "award_types" VALUES (316,'Trefoil',100,22,NULL);
INSERT INTO "award_types" VALUES (317,'Promise of the Outlands',100,22,NULL);
INSERT INTO "award_types" VALUES (318,'Azure Mullet of the Outlands',100,22,NULL);
INSERT INTO "award_types" VALUES (319,'Sigillum Principis',100,2,0);
INSERT INTO "award_types" VALUES (320,'Star and Lily',300,17,NULL);
INSERT INTO "award_types" VALUES (321,'Prometheus',300,17,NULL);
INSERT INTO "award_types" VALUES (322,'Burdened Tyger, Order of the',100,16,'');
INSERT INTO "award_types" VALUES (323,'Queen''s Honor of Distinction',100,16,NULL);
INSERT INTO "award_types" VALUES (324,'Companion of the Tyger of the East',100,16,NULL);
INSERT INTO "award_types" VALUES (325,'Order of the Emerald Seas',100,23,NULL);
INSERT INTO "award_types" VALUES (326,'Order of the Argent Morningstar of Trimaris',100,23,NULL);
INSERT INTO "award_types" VALUES (327,'Crown''s Order of Gratitude',100,23,NULL);
INSERT INTO "award_types" VALUES (328,'Order of Trimarian Gratitude',100,23,NULL);
INSERT INTO "award_types" VALUES (329,'Defense, Order of',700,1,1);
INSERT INTO "award_types" VALUES (330,'Luna',100,27,1);
INSERT INTO "award_types" VALUES (331,'Beacon of the Desert',100,10,NULL);
INSERT INTO "award_types" VALUES (332,'Star of the Desert-Azure',100,10,NULL);
INSERT INTO "award_types" VALUES (333,'Flower of the Desert',100,10,NULL);
INSERT INTO "award_types" VALUES (334,'Tjelvars Eld',100,25,NULL);
INSERT INTO "award_types" VALUES (335,'Silver Pegasus',100,17,NULL);
INSERT INTO "award_types" VALUES (336,'Golden Poyntel',100,17,NULL);
INSERT INTO "award_types" VALUES (337,'Nordmarks Hare',100,3,NULL);
INSERT INTO "award_types" VALUES (338,'Kings Council',100,9,NULL);
INSERT INTO "award_types" VALUES (339,'Gryphons Heart',100,9,NULL);
INSERT INTO "award_types" VALUES (340,'Vaaleanpunainen virvaliekki (Pink)',100,4,1);
INSERT INTO "award_types" VALUES (341,'Saint Egons Heart, Award of',100,30,'');
INSERT INTO "award_types" VALUES (342,'Dana the Brave of Gotvik, Award of',100,30,'');
INSERT INTO "award_types" VALUES (343,'Ragenhild the Wise of Gotvik, Award of',100,30,'');
INSERT INTO "award_types" VALUES (344,'Ladle of Saint Sigerid of Gotvik, Award of',100,30,'');
INSERT INTO "award_types" VALUES (345,'Arrow of Saint Egon of Gotvik, Award of',100,30,'');
INSERT INTO "award_types" VALUES (346,'Archaic Fewmet, Order of the',100,13,NULL);
INSERT INTO "award_types" VALUES (347,'Taillefer, Order of',100,17,NULL);
INSERT INTO "award_types" VALUES (348,'Enhörning (Unicorn)',100,3,NULL);
INSERT INTO "award_types" VALUES (349,'Esprit de Corps',100,10,NULL);
INSERT INTO "award_types" VALUES (350,'Spear of the Sun',100,10,NULL);
INSERT INTO "award_types" VALUES (351,'Rising Star of Ansteorra',100,8,NULL);
INSERT INTO "award_types" VALUES (352,'Pilgrims of Gotvik, Order of the',100,30,'');
INSERT INTO "award_types" VALUES (353,'Silver Dolphin of Gotvik, Order of the',100,30,'');
INSERT INTO "award_types" VALUES (354,'King''s Favor of Calontir',100,13,NULL);
INSERT INTO "award_types" VALUES (355,'Nordbandr',100,26,NULL);
INSERT INTO "award_types" VALUES (356,'Griffin and Sword, Award of the',200,26,NULL);
INSERT INTO "award_types" VALUES (357,'Cygnus, Award of the',200,26,NULL);
INSERT INTO "award_types" VALUES (358,'Golden Peacock, Order of the',200,26,NULL);
INSERT INTO "award_types" VALUES (359,'Cygni, Ordo',500,2,1);
INSERT INTO "award_types" VALUES (360,'Hirundinis, Ordo',500,2,1);
INSERT INTO "award_types" VALUES (361,'Alae, Ordo',500,2,1);
INSERT INTO "award_types" VALUES (362,'Lejon (Lion)',100,3,NULL);
INSERT INTO "award_types" VALUES (363,'Princess''s Talon of Favor',100,31,NULL);
INSERT INTO "award_types" VALUES (364,'Saint Hild, Order of',100,27,1);
INSERT INTO "award_types" VALUES (365,'Silver Gauntlet of Knights Crossing, Order of the',100,5,1);
INSERT INTO "award_types" VALUES (366,'Golden Flame',100,32,NULL);
INSERT INTO "award_types" VALUES (367,'Princess'' Knott',100,32,NULL);
INSERT INTO "award_types" VALUES (368,'Throne''s Favor',100,7,NULL);
INSERT INTO "award_types" VALUES (369,'Carp',100,7,NULL);
INSERT INTO "award_types" VALUES (370,'Elder',100,32,NULL);
INSERT INTO "award_types" VALUES (371,'Royal Scribal Favor',100,7,NULL);
INSERT INTO "award_types" VALUES (372,'Onore del Ponte d''Oro',100,33,NULL);
INSERT INTO "award_types" VALUES (373,'Baroness Champion of Chivalry',100,34,NULL);
INSERT INTO "award_types" VALUES (374,'Seraphic Star',100,34,NULL);
INSERT INTO "award_types" VALUES (375,'Red Raven Downs',100,34,NULL);
INSERT INTO "award_types" VALUES (376,'Golden Poppy',100,34,NULL);
INSERT INTO "award_types" VALUES (377,'Towers of Dreiburgen',100,34,NULL);
INSERT INTO "award_types" VALUES (378,'Order of the Queen''s Grace',100,34,NULL);
INSERT INTO "award_types" VALUES (379,'Lady of the Solar Leaf',100,34,NULL);
INSERT INTO "award_types" VALUES (380,'Founding Baroness Far Isles',100,34,NULL);
INSERT INTO "award_types" VALUES (381,'Aristotelis Discipuli',100,34,NULL);
INSERT INTO "award_types" VALUES (382,'Lamp',100,34,NULL);
INSERT INTO "award_types" VALUES (383,'Signum Reginae',100,34,NULL);
INSERT INTO "award_types" VALUES (384,'Solar Phoenix',100,34,NULL);
INSERT INTO "award_types" VALUES (385,'Gilded Leaf of Caerthe',100,22,'');
INSERT INTO "award_types" VALUES (386,'Halberd of Bryn Gwlad',100,34,NULL);
INSERT INTO "award_types" VALUES (387,'Coils Muses',100,34,NULL);
INSERT INTO "award_types" VALUES (388,'Coils Tripaliare',100,34,NULL);
INSERT INTO "award_types" VALUES (389,'Founding Baron Knights Crossing',100,34,NULL);
INSERT INTO "award_types" VALUES (390,'Founding Baroness Knights Crossing',100,34,NULL);
INSERT INTO "award_types" VALUES (391,'Wind-Blown Leaf',100,34,NULL);
INSERT INTO "award_types" VALUES (392,'Princess Token',100,34,NULL);
INSERT INTO "award_types" VALUES (393,'Golden Comet',100,34,NULL);
INSERT INTO "award_types" VALUES (394,'Keeper of the Solar Heart',100,34,NULL);
INSERT INTO "award_types" VALUES (395,'Gryphons Plume',100,34,NULL);
INSERT INTO "award_types" VALUES (396,'Oleander',100,34,NULL);
INSERT INTO "award_types" VALUES (397,'Tygers Cub',100,34,NULL);
INSERT INTO "award_types" VALUES (398,'Royal Gauntlet',100,34,NULL);
INSERT INTO "award_types" VALUES (399,'Premier Wheel',100,34,NULL);
INSERT INTO "award_types" VALUES (400,'Silver Needle',100,34,NULL);
INSERT INTO "award_types" VALUES (401,'Berries',100,34,NULL);
INSERT INTO "award_types" VALUES (402,'Aspen of Caerthe',100,22,'');
INSERT INTO "award_types" VALUES (403,'Founding Baroness Darkwater',100,34,NULL);
INSERT INTO "award_types" VALUES (404,'Trimarian Sword',100,34,NULL);
INSERT INTO "award_types" VALUES (405,'Order of the Queen''s Favour',100,34,NULL);
INSERT INTO "award_types" VALUES (406,'Terpsichore',100,34,NULL);
INSERT INTO "award_types" VALUES (407,'Triskele',100,34,NULL);
INSERT INTO "award_types" VALUES (408,'Silver Trident',100,34,NULL);
INSERT INTO "award_types" VALUES (409,'Friendly Castle',100,34,NULL);
INSERT INTO "award_types" VALUES (410,'Salamander',100,34,NULL);
INSERT INTO "award_types" VALUES (411,'Pharos',100,34,NULL);
INSERT INTO "award_types" VALUES (412,'Fellow o/t University of Atlantia',100,34,NULL);
INSERT INTO "award_types" VALUES (413,'Seahorse',100,34,NULL);
INSERT INTO "award_types" VALUES (415,'Silver Roundel',100,34,NULL);
INSERT INTO "award_types" VALUES (416,'Founding Baron Nordmark',100,34,NULL);
INSERT INTO "award_types" VALUES (417,'Founding Baron Far West',100,34,NULL);
INSERT INTO "award_types" VALUES (418,'Attic Helm',100,34,NULL);
INSERT INTO "award_types" VALUES (419,'Bearer of the Burdened Bouget',100,34,NULL);
INSERT INTO "award_types" VALUES (420,'Empty Shell',100,34,NULL);
INSERT INTO "award_types" VALUES (421,'Hibiscus',100,34,NULL);
INSERT INTO "award_types" VALUES (422,'Oriental Dragon',100,34,NULL);
INSERT INTO "award_types" VALUES (423,'Barons Order for Excellence',100,34,NULL);
INSERT INTO "award_types" VALUES (424,'Comp. of St James de Compostella',100,34,NULL);
INSERT INTO "award_types" VALUES (425,'Golden Staple',100,34,NULL);
INSERT INTO "award_types" VALUES (426,'Stags Heart',100,34,NULL);
INSERT INTO "award_types" VALUES (427,'Charter Hidden Treasure',100,34,NULL);
INSERT INTO "award_types" VALUES (428,'Astrum Australis',100,34,NULL);
INSERT INTO "award_types" VALUES (429,'Silver Nib',100,34,NULL);
INSERT INTO "award_types" VALUES (430,'Flaming Brand',100,34,NULL);
INSERT INTO "award_types" VALUES (431,'1e Commander of the Guardians of A.',100,34,NULL);
INSERT INTO "award_types" VALUES (432,'Sovereign''s Pleasure',100,34,NULL);
INSERT INTO "award_types" VALUES (433,'1e Lord Defender of Mons Tonitrus',100,34,NULL);
INSERT INTO "award_types" VALUES (434,'Founding Baroness Mons Tonitrus',100,34,NULL);
INSERT INTO "award_types" VALUES (435,'Premier Guardian of the Saguaro',100,34,NULL);
INSERT INTO "award_types" VALUES (436,'Premier Keeper of the Silver Morion',100,34,NULL);
INSERT INTO "award_types" VALUES (437,'Premier Sable Chevronels',100,34,NULL);
INSERT INTO "award_types" VALUES (438,'Premier Sable Harps',100,34,NULL);
INSERT INTO "award_types" VALUES (439,'Premier Silver Thunderbolt',100,34,NULL);
INSERT INTO "award_types" VALUES (440,'Bearer of the Queens Cypher: DR',100,34,NULL);
INSERT INTO "award_types" VALUES (441,'Sea Stag, Order of',100,34,NULL);
INSERT INTO "award_types" VALUES (442,'Morning Star',100,34,NULL);
INSERT INTO "award_types" VALUES (443,'Corolla Moralis',100,34,NULL);
INSERT INTO "award_types" VALUES (444,'Bearer of the Queens Cypher: AR',100,34,NULL);
INSERT INTO "award_types" VALUES (445,'Argent Estoile, Order of the',100,23,'');
INSERT INTO "award_types" VALUES (446,'Argent Scales',100,34,NULL);
INSERT INTO "award_types" VALUES (447,'Esprit de Soleil',100,34,NULL);
INSERT INTO "award_types" VALUES (448,'Sable Chevronels',100,34,NULL);
INSERT INTO "award_types" VALUES (449,'Sable Harps',100,34,NULL);
INSERT INTO "award_types" VALUES (450,'Bearer of the Kings Sygil',100,34,NULL);
INSERT INTO "award_types" VALUES (451,'Commander of the Solar Phoenix',100,34,NULL);
INSERT INTO "award_types" VALUES (452,'Guardian of the Saguaro',100,34,NULL);
INSERT INTO "award_types" VALUES (453,'Keeper of the Silver Morion',100,34,NULL);
INSERT INTO "award_types" VALUES (454,'Lady Defender of Mons Tonitrus',100,34,NULL);
INSERT INTO "award_types" VALUES (455,'Silver Thunderbolt',100,34,NULL);
INSERT INTO "award_types" VALUES (456,'Princess Order of Grace',100,34,NULL);
INSERT INTO "award_types" VALUES (457,'Sergeant-at-arms',100,34,NULL);
INSERT INTO "award_types" VALUES (458,'Corrola Aulica',100,34,NULL);
INSERT INTO "award_types" VALUES (459,'Founding Baroness Aarnimetsä',100,2,0);
INSERT INTO "award_types" VALUES (460,'Founding Baron Drei Eichen',100,2,0);
INSERT INTO "award_types" VALUES (461,'Founding Baroness Drei Eichen',100,2,0);
INSERT INTO "award_types" VALUES (462,'Undine',100,34,NULL);
INSERT INTO "award_types" VALUES (463,'Princess Chyper',100,34,NULL);
INSERT INTO "award_types" VALUES (464,'Dragon''s Steel - Resigned!',100,34,NULL);
INSERT INTO "award_types" VALUES (465,'Crystal Swan',100,34,NULL);
INSERT INTO "award_types" VALUES (466,'Griffin and Sword, Order of the',100,34,NULL);
INSERT INTO "award_types" VALUES (467,'Princess',100,34,NULL);
INSERT INTO "award_types" VALUES (468,'Golden Book of Knights Crossing, Order of the',100,5,1);
INSERT INTO "award_types" VALUES (469,'Jeweled Ring, Order of the',100,28,'');
INSERT INTO "award_types" VALUES (470,'Bard''s Laureate, Order of the',100,23,'');
INSERT INTO "award_types" VALUES (471,'Serpent''s Gem, Order of the',100,35,'');
INSERT INTO "award_types" VALUES (472,'House of the Serpent''s Tongue, Order of the',100,35,'');
INSERT INTO "award_types" VALUES (473,'Herald''s Tressure, Order of the',100,23,'');
INSERT INTO "award_types" VALUES (474,'Acorn''s Glade, Order of the',100,36,'');
INSERT INTO "award_types" VALUES (475,'Boreas, Order of the',100,37,1);
INSERT INTO "award_types" VALUES (476,'Kitty Hawk, Order of the',100,37,1);
INSERT INTO "award_types" VALUES (477,'Eurus, Order of the',100,37,'');
INSERT INTO "award_types" VALUES (478,'Squamifer''s Fortune',100,38,1);
INSERT INTO "award_types" VALUES (479,'Crystal of Glymm Mere',100,39,'');
INSERT INTO "award_types" VALUES (480,'Sweet of Glymm Mere',100,39,'');
INSERT INTO "award_types" VALUES (481,'Sterne, Gesellschaft der',100,5,1);
INSERT INTO "award_types" VALUES (482,'Boarsbane, Order of the',100,40,1);
INSERT INTO "award_types" VALUES (483,'Saint Roch, Companion of',100,41,'');
INSERT INTO "award_types" VALUES (484,'Silver Nautilus, Award of the',100,11,'');
INSERT INTO "award_types" VALUES (485,'Sable Lion of Caerthe, Award of the',300,22,1);
INSERT INTO "award_types" VALUES (486,'Star of the Desert, Award of the',100,10,'');
INSERT INTO "award_types" VALUES (487,'Golden Oak, Award of the',100,7,'');
INSERT INTO "award_types" VALUES (488,'Defender of the Hart',100,7,'');
INSERT INTO "award_types" VALUES (489,'Tuatha de Charbhad Óir',100,42,1);
INSERT INTO "award_types" VALUES (490,'Tuatha de Lámh Airgid',100,42,1);
INSERT INTO "award_types" VALUES (491,'Tuatha de Dillon',100,42,1);
INSERT INTO "award_types" VALUES (492,'Hero''s Portion',100,42,0);
INSERT INTO "award_types" VALUES (493,'Sun and Pearl, Order of the',100,27,NULL);
INSERT INTO "award_types" VALUES (494,'Tuatha de Lunula',100,42,1);
INSERT INTO "award_types" VALUES (495,'Tuatha de Clogh Ogham',100,42,1);
INSERT INTO "award_types" VALUES (496,'Tuatha de Cú Seirbnís',100,42,1);
INSERT INTO "award_types" VALUES (497,'Tuatha de Setanta',100,42,1);
INSERT INTO "award_types" VALUES (498,'Tuatha de Craiftine',100,42,1);
INSERT INTO "award_types" VALUES (499,'Tuatha de Dhéise',100,42,1);
INSERT INTO "award_types" VALUES (500,'Tuatha Corn na Cogadh',100,42,1);
INSERT INTO "award_types" VALUES (501,'Tuatha de Filí',100,42,1);
INSERT INTO "award_types" VALUES (502,'Tuatha d''Coire',100,42,1);
INSERT INTO "award_types" VALUES (503,'Sigil of Æthelmearc',100,6,0);
INSERT INTO "award_types" VALUES (504,'Howling Wolf (Principal), Companion of the ',100,6,0);
INSERT INTO "award_types" VALUES (505,'Golden Mirror, Companion of the ',200,6,0);
INSERT INTO "award_types" VALUES (506,'Golden Thorn, Companion of the ',100,6,0);
INSERT INTO "award_types" VALUES (507,'Award of the Shields Knot ',100,11,0);
INSERT INTO "award_types" VALUES (508,'Award of the Shark''s Tooth ',100,11,0);
INSERT INTO "award_types" VALUES (509,'Companion of the Sword Knot ',100,11,0);
INSERT INTO "award_types" VALUES (510,'Companion of the Coill''s Champions ',100,11,0);
INSERT INTO "award_types" VALUES (511,'Companion of the Gordian Knot ',100,11,0);
INSERT INTO "award_types" VALUES (512,'Wreath of Athena',100,24,0);
INSERT INTO "award_types" VALUES (513,'Corolla Aulica',100,24,0);
INSERT INTO "award_types" VALUES (514,'Princess'' Favor ',100,24,0);
INSERT INTO "award_types" VALUES (515,'Oak Tree of Enrichment ',100,24,0);
INSERT INTO "award_types" VALUES (516,'Coeur d''Azur ',100,24,0);
INSERT INTO "award_types" VALUES (517,'Coronet''s Favor',100,24,0);
INSERT INTO "award_types" VALUES (518,'Award of the Golden Knot',100,11,0);
INSERT INTO "award_types" VALUES (519,'Excellence of Nottinghill Coill ',100,11,0);
INSERT INTO "crowns" VALUES (2,'-');
INSERT INTO "crowns" VALUES (3,'- ( ?)');
INSERT INTO "crowns" VALUES (4,'- ( Catherine or Alienor)');
INSERT INTO "crowns" VALUES (5,'- ( Gwenllian or Jeanmaire)');
INSERT INTO "crowns" VALUES (6,'- ( Gwynna or Morgan)');
INSERT INTO "crowns" VALUES (7,'- ( Idunn or Leia)');
INSERT INTO "crowns" VALUES (8,'- ( Ivar or Stefan)');
INSERT INTO "crowns" VALUES (9,'- ( Kaylitha or Gwynna)');
INSERT INTO "crowns" VALUES (10,'- ( Regina or Caitriona)');
INSERT INTO "crowns" VALUES (11,'- ( Richard or Wulfbrand)');
INSERT INTO "crowns" VALUES (12,'- ( Silesia or Bettina)');
INSERT INTO "crowns" VALUES (13,'- (?)');
INSERT INTO "crowns" VALUES (14,'- (BMDL, East)');
INSERT INTO "crowns" VALUES (15,'- (Charitee or Ivone)');
INSERT INTO "crowns" VALUES (16,'- (East?)');
INSERT INTO "crowns" VALUES (17,'- (South Meridies)');
INSERT INTO "crowns" VALUES (18,'Aarnimetsä');
INSERT INTO "crowns" VALUES (19,'Adelicia');
INSERT INTO "crowns" VALUES (20,'Agnes');
INSERT INTO "crowns" VALUES (21,'Alaric');
INSERT INTO "crowns" VALUES (22,'Alaric and Nerissa');
INSERT INTO "crowns" VALUES (23,'Alessandra Melusine');
INSERT INTO "crowns" VALUES (24,'Alexander and Katya');
INSERT INTO "crowns" VALUES (25,'Alienor');
INSERT INTO "crowns" VALUES (26,'An Tir');
INSERT INTO "crowns" VALUES (27,'Anna');
INSERT INTO "crowns" VALUES (28,'Ansteorra');
INSERT INTO "crowns" VALUES (29,'Artemesia');
INSERT INTO "crowns" VALUES (30,'Aryanhwy');
INSERT INTO "crowns" VALUES (31,'Atenveldt');
INSERT INTO "crowns" VALUES (32,'Caerthe, Barony of');
INSERT INTO "crowns" VALUES (33,'Loch Salann, Barony of');
INSERT INTO "crowns" VALUES (34,'Mons Tinitrus, Barony of');
INSERT INTO "crowns" VALUES (35,'Atlantia');
INSERT INTO "crowns" VALUES (36,'Caer Mear, Barony of');
INSERT INTO "crowns" VALUES (37,'Nottinghill Coill, Barony of');
INSERT INTO "crowns" VALUES (38,'Windmasters Hill, Barony of');
INSERT INTO "crowns" VALUES (39,'Atlantia (Galmr and Caterina)');
INSERT INTO "crowns" VALUES (40,'Avacal');
INSERT INTO "crowns" VALUES (41,'Axel');
INSERT INTO "crowns" VALUES (42,'Axel and Jeanmaire');
INSERT INTO "crowns" VALUES (43,'Bearengaer and Nige');
INSERT INTO "crowns" VALUES (44,'Bettina');
INSERT INTO "crowns" VALUES (45,'Bryon');
INSERT INTO "crowns" VALUES (46,'Bryon and Silesia');
INSERT INTO "crowns" VALUES (47,'Cadogan');
INSERT INTO "crowns" VALUES (48,'Cadogan and Eufemia');
INSERT INTO "crowns" VALUES (49,'Caid');
INSERT INTO "crowns" VALUES (50,'Dreiburgen, Barony of');
INSERT INTO "crowns" VALUES (51,'Caitriona');
INSERT INTO "crowns" VALUES (52,'Calontir');
INSERT INTO "crowns" VALUES (53,'Caoimhe');
INSERT INTO "crowns" VALUES (54,'Catheryn');
INSERT INTO "crowns" VALUES (55,'Cecilia');
INSERT INTO "crowns" VALUES (56,'Cian');
INSERT INTO "crowns" VALUES (57,'Cian and Catherine');
INSERT INTO "crowns" VALUES (58,'Cynagua');
INSERT INTO "crowns" VALUES (59,'Cynaugua');
INSERT INTO "crowns" VALUES (60,'Dafydd and Morgan');
INSERT INTO "crowns" VALUES (61,'David and Catherine');
INSERT INTO "crowns" VALUES (62,'David and Catheryn');
INSERT INTO "crowns" VALUES (63,'Doran and Vincetta');
INSERT INTO "crowns" VALUES (65,'Drei Eichen');
INSERT INTO "crowns" VALUES (66,'Ealdormere');
INSERT INTO "crowns" VALUES (67,'Eanor');
INSERT INTO "crowns" VALUES (68,'East');
INSERT INTO "crowns" VALUES (69,'East (Barony of Myrkewood)');
INSERT INTO "crowns" VALUES (70,'East (Barony of Ostgardr)');
INSERT INTO "crowns" VALUES (71,'East (Lea)');
INSERT INTO "crowns" VALUES (72,'East (Lucan and Jana)');
INSERT INTO "crowns" VALUES (73,'East (Rowan)');
INSERT INTO "crowns" VALUES (74,'East (Ruslan and Margaret)');
INSERT INTO "crowns" VALUES (75,'Edouard');
INSERT INTO "crowns" VALUES (76,'Edouard and Eanor');
INSERT INTO "crowns" VALUES (77,'Eleanora');
INSERT INTO "crowns" VALUES (78,'Eleonora');
INSERT INTO "crowns" VALUES (79,'Elffin');
INSERT INTO "crowns" VALUES (80,'Elffin and Alessandra Melusine');
INSERT INTO "crowns" VALUES (81,'Elffin and Signy');
INSERT INTO "crowns" VALUES (82,'Elffin and Vanna');
INSERT INTO "crowns" VALUES (83,'Eufemia');
INSERT INTO "crowns" VALUES (84,'EzaBella');
INSERT INTO "crowns" VALUES (85,'Fiona');
INSERT INTO "crowns" VALUES (86,'Galen');
INSERT INTO "crowns" VALUES (87,'Galen and Kaylitha');
INSERT INTO "crowns" VALUES (88,'Gareth');
INSERT INTO "crowns" VALUES (89,'Gareth and Idunn');
INSERT INTO "crowns" VALUES (90,'Garick and Talitha');
INSERT INTO "crowns" VALUES (91,'Gerhardt');
INSERT INTO "crowns" VALUES (92,'Gerhardt and Aurelia');
INSERT INTO "crowns" VALUES (93,'Gerhardt and Judith');
INSERT INTO "crowns" VALUES (94,'Giles');
INSERT INTO "crowns" VALUES (95,'Giles and EzaBella');
INSERT INTO "crowns" VALUES (96,'Gleann Abhann');
INSERT INTO "crowns" VALUES (97,'Gotvik');
INSERT INTO "crowns" VALUES (98,'Gwenllian');
INSERT INTO "crowns" VALUES (99,'Gwenllian and Stefan');
INSERT INTO "crowns" VALUES (100,'Gwynna');
INSERT INTO "crowns" VALUES (101,'Gyth');
INSERT INTO "crowns" VALUES (102,'Honor');
INSERT INTO "crowns" VALUES (103,'Ian');
INSERT INTO "crowns" VALUES (104,'Ian and Charitee');
INSERT INTO "crowns" VALUES (105,'Idunn');
INSERT INTO "crowns" VALUES (106,'Insulae Draconis');
INSERT INTO "crowns" VALUES (107,'Isabel');
INSERT INTO "crowns" VALUES (108,'Isabetta');
INSERT INTO "crowns" VALUES (109,'Ivar');
INSERT INTO "crowns" VALUES (110,'Ivar and Kathleen');
INSERT INTO "crowns" VALUES (111,'Ivone');
INSERT INTO "crowns" VALUES (112,'Izabella');
INSERT INTO "crowns" VALUES (113,'Jahanara');
INSERT INTO "crowns" VALUES (114,'Jahn and Tuiren');
INSERT INTO "crowns" VALUES (115,'Jeanmaire');
INSERT INTO "crowns" VALUES (116,'Joedda');
INSERT INTO "crowns" VALUES (117,'John');
INSERT INTO "crowns" VALUES (118,'John and Honor');
INSERT INTO "crowns" VALUES (119,'Jovi');
INSERT INTO "crowns" VALUES (120,'Judith');
INSERT INTO "crowns" VALUES (121,'Jurgan');
INSERT INTO "crowns" VALUES (122,'Jurgan and Lilliard');
INSERT INTO "crowns" VALUES (123,'Justin and Gyth');
INSERT INTO "crowns" VALUES (124,'Karl');
INSERT INTO "crowns" VALUES (125,'Karl and Bettina');
INSERT INTO "crowns" VALUES (126,'Karl and Leia');
INSERT INTO "crowns" VALUES (127,'Katharina');
INSERT INTO "crowns" VALUES (128,'Kathleen');
INSERT INTO "crowns" VALUES (129,'Kaylitha');
INSERT INTO "crowns" VALUES (130,'Knights Crossing');
INSERT INTO "crowns" VALUES (131,'Leia');
INSERT INTO "crowns" VALUES (132,'Lief');
INSERT INTO "crowns" VALUES (133,'Lief and Morrigan');
INSERT INTO "crowns" VALUES (134,'Lochac');
INSERT INTO "crowns" VALUES (135,'Rowany, Barony of');
INSERT INTO "crowns" VALUES (136,'Lucilla');
INSERT INTO "crowns" VALUES (137,'Makarius');
INSERT INTO "crowns" VALUES (138,'Makarius and Izabella');
INSERT INTO "crowns" VALUES (139,'Marcus');
INSERT INTO "crowns" VALUES (140,'Marcus and Anna');
INSERT INTO "crowns" VALUES (141,'Marcus and Cecilia');
INSERT INTO "crowns" VALUES (142,'Margerite');
INSERT INTO "crowns" VALUES (143,'Matthew');
INSERT INTO "crowns" VALUES (144,'Matthew and Alienor');
INSERT INTO "crowns" VALUES (145,'Matthew and Anna');
INSERT INTO "crowns" VALUES (146,'Maximilian');
INSERT INTO "crowns" VALUES (147,'Maximilian and Margerite');
INSERT INTO "crowns" VALUES (148,'Meridies');
INSERT INTO "crowns" VALUES (149,'Michael');
INSERT INTO "crowns" VALUES (150,'Michael and Alessandra Melusine');
INSERT INTO "crowns" VALUES (151,'Michael and Moira');
INSERT INTO "crowns" VALUES (152,'Middle');
INSERT INTO "crowns" VALUES (153,'Flaming Gryphon, Barony of');
INSERT INTO "crowns" VALUES (154,'Middle (Palymar and Aislinn)');
INSERT INTO "crowns" VALUES (155,'Mists');
INSERT INTO "crowns" VALUES (156,'Moira');
INSERT INTO "crowns" VALUES (157,'Morales');
INSERT INTO "crowns" VALUES (158,'Morales and Agnes');
INSERT INTO "crowns" VALUES (159,'Morgan');
INSERT INTO "crowns" VALUES (160,'Morgan and Alienor');
INSERT INTO "crowns" VALUES (161,'Morrigan');
INSERT INTO "crowns" VALUES (162,'Myles');
INSERT INTO "crowns" VALUES (163,'Myles and Katharina');
INSERT INTO "crowns" VALUES (164,'Myles and Katherina');
INSERT INTO "crowns" VALUES (165,'Nerissa');
INSERT INTO "crowns" VALUES (166,'Nige');
INSERT INTO "crowns" VALUES (167,'Nordmark');
INSERT INTO "crowns" VALUES (168,'Northshield');
INSERT INTO "crowns" VALUES (169,'Oertha');
INSERT INTO "crowns" VALUES (170,'Outlands');
INSERT INTO "crowns" VALUES (171,'Outlands (Citadel of the Southern Pass)');
INSERT INTO "crowns" VALUES (172,'Padraig');
INSERT INTO "crowns" VALUES (173,'Padraig and Elsa');
INSERT INTO "crowns" VALUES (174,'Paul');
INSERT INTO "crowns" VALUES (175,'Paul and Aryanhwy');
INSERT INTO "crowns" VALUES (176,'Peregrine');
INSERT INTO "crowns" VALUES (177,'Peregrine and Alessandra Melusine');
INSERT INTO "crowns" VALUES (178,'Ponte Alto, Barony of');
INSERT INTO "crowns" VALUES (179,'Prothall');
INSERT INTO "crowns" VALUES (180,'Prothall and Cecilia');
INSERT INTO "crowns" VALUES (181,'Raim and Gwynna');
INSERT INTO "crowns" VALUES (182,'Raim and Regina');
INSERT INTO "crowns" VALUES (183,'Regina');
INSERT INTO "crowns" VALUES (184,'Richard');
INSERT INTO "crowns" VALUES (185,'Richard and Joedda');
INSERT INTO "crowns" VALUES (186,'Signy');
INSERT INTO "crowns" VALUES (187,'Silesia');
INSERT INTO "crowns" VALUES (188,'Siobhan');
INSERT INTO "crowns" VALUES (189,'Siridean');
INSERT INTO "crowns" VALUES (190,'Siridean and Jahanara');
INSERT INTO "crowns" VALUES (191,'Stefan');
INSERT INTO "crowns" VALUES (192,'Styringheim');
INSERT INTO "crowns" VALUES (193,'Summits');
INSERT INTO "crowns" VALUES (194,'Sun');
INSERT INTO "crowns" VALUES (195,'Sven');
INSERT INTO "crowns" VALUES (196,'Sven and Jovi');
INSERT INTO "crowns" VALUES (197,'Sven and Siobhan');
INSERT INTO "crowns" VALUES (198,'Sven and Thora');
INSERT INTO "crowns" VALUES (199,'Talitha');
INSERT INTO "crowns" VALUES (200,'Thora');
INSERT INTO "crowns" VALUES (201,'ThorvaldR and Tomoe');
INSERT INTO "crowns" VALUES (202,'Thorvaldr');
INSERT INTO "crowns" VALUES (203,'Thorvaldr and Fiona');
INSERT INTO "crowns" VALUES (204,'Thorvaldr and Tofa');
INSERT INTO "crowns" VALUES (205,'Timmeke and Adelicia');
INSERT INTO "crowns" VALUES (206,'Timoch and Adelicia');
INSERT INTO "crowns" VALUES (207,'Tir Righ');
INSERT INTO "crowns" VALUES (208,'Tofa');
INSERT INTO "crowns" VALUES (209,'Tomoe');
INSERT INTO "crowns" VALUES (210,'Trimaris');
INSERT INTO "crowns" VALUES (211,'UlfR');
INSERT INTO "crowns" VALUES (212,'UlfR and Caoimhe');
INSERT INTO "crowns" VALUES (213,'Ulric and Eleonora');
INSERT INTO "crowns" VALUES (214,'Vanna');
INSERT INTO "crowns" VALUES (215,'Vitus');
INSERT INTO "crowns" VALUES (216,'Vitus and Eleanora');
INSERT INTO "crowns" VALUES (217,'Vitus and Isabel');
INSERT INTO "crowns" VALUES (218,'West');
INSERT INTO "crowns" VALUES (219,'West (Barony of Angels, Caid)');
INSERT INTO "crowns" VALUES (220,'West (Palatine Barony of Far West)');
INSERT INTO "crowns" VALUES (221,'William');
INSERT INTO "crowns" VALUES (222,'William and Isabetta');
INSERT INTO "crowns" VALUES (223,'Wlfric and Eira');
INSERT INTO "crowns" VALUES (224,'Wolf and Caitriona');
INSERT INTO "crowns" VALUES (225,'Wulfbrand');
INSERT INTO "crowns" VALUES (226,'Wulfbrand and Lucilla');
INSERT INTO "crowns" VALUES (227,'Wulfric and Eira');
INSERT INTO "crowns" VALUES (228,'Yoshina');
INSERT INTO "crowns" VALUES (229,'Yoshina and Ivone');
INSERT INTO "crowns" VALUES (230,'Æthelmearc');
INSERT INTO "crowns" VALUES (231,'An Crosaire, Barony of');
INSERT INTO "crowns" VALUES (232,'Darkwater, Barony of');
INSERT INTO "crowns" VALUES (233,'Ile du Dragon Dormant, Barony of');
INSERT INTO "crowns" VALUES (234,'Glymm Mere');
INSERT INTO "crowns" VALUES (235,'Red Spears, Barony of');
INSERT INTO "crowns" VALUES (236,'Æiríkr and Jacquelyna');
INSERT INTO "crowns" VALUES (237,'Æiríkr');
INSERT INTO "crowns" VALUES (238,'Jacquelyna');
INSERT INTO "crowns" VALUES (239,'Stierbach, Barony of');
INSERT INTO "crowns" VALUES (240,'Wealdsmere, Barony of');
INSERT INTO "crowns" VALUES (241,'Silverhart, Barony of');
INSERT INTO "crowns" VALUES (242,'Eplaheimr, Barony of');
INSERT INTO "crowns" VALUES (243,'Avery & Cornelia');
INSERT INTO "crowns" VALUES (244,'Morales & Eila');
INSERT INTO "reigns" VALUES (1,'Jahn','Tuiren','1980-06-09','1981-01-10');
INSERT INTO "reigns" VALUES (2,'Bearengaer','Nige','1981-01-10','1981-06-06');
INSERT INTO "reigns" VALUES (3,'David','Catherine','1981-06-06','1982-01-02');
INSERT INTO "reigns" VALUES (4,'Doran','Vincetta','1982-01-02','1982-06-26');
INSERT INTO "reigns" VALUES (5,'Raim','Regina','1982-06-26','1983-01-08');
INSERT INTO "reigns" VALUES (6,'Wolf','Caitriona','1983-01-08','1983-07-09');
INSERT INTO "reigns" VALUES (7,'Alexander','Katya','1983-07-09','1984-01-28');
INSERT INTO "reigns" VALUES (8,'Galen','Kaylitha','1984-01-28','1984-06-23');
INSERT INTO "reigns" VALUES (9,'Raim','Gwynna','1984-06-23','1985-01-05');
INSERT INTO "reigns" VALUES (10,'Dafydd','Morgan','1985-01-05','1985-06-08');
INSERT INTO "reigns" VALUES (11,'Richard','Joedda','1985-06-08','1986-01-04');
INSERT INTO "reigns" VALUES (12,'Wulfbrand','Lucilla','1986-01-04','1986-06-21');
INSERT INTO "reigns" VALUES (13,'Justin','Gyth','1986-06-21','1987-01-10');
INSERT INTO "reigns" VALUES (14,'Ulric','Eleonora','1987-01-10','1987-06-20');
INSERT INTO "reigns" VALUES (15,'Ivar','Kathleen','1987-06-20','1988-01-09');
INSERT INTO "reigns" VALUES (16,'Gwenllian','Stefan','1988-01-09','1988-06-18');
INSERT INTO "reigns" VALUES (17,'Axel','Jeanmaire','1988-06-18','1989-01-07');
INSERT INTO "reigns" VALUES (18,'Ian','Charitee','1989-01-07','1989-06-24');
INSERT INTO "reigns" VALUES (19,'Yoshina','Ivone','1989-06-24','1990-01-06');
INSERT INTO "reigns" VALUES (20,'Bryon','Silesia','1990-01-06','1990-06-16');
INSERT INTO "reigns" VALUES (21,'Karl','Bettina','1990-06-16','1991-01-05');
INSERT INTO "reigns" VALUES (22,'Cian','Catherine','1991-01-05','1991-06-22');
INSERT INTO "reigns" VALUES (23,'Morgan','Alienor','1991-06-22','1992-01-04');
INSERT INTO "reigns" VALUES (24,'Myles','Katherina','1992-01-04','1992-06-20');
INSERT INTO "reigns" VALUES (25,'Gareth','Idunn','1992-06-20','1993-01-09');
INSERT INTO "reigns" VALUES (26,'Karl','Leia','1993-01-09','1993-06-05');
INSERT INTO "reigns" VALUES (27,'Elffin','Vanna','1993-06-05','1994-01-01');
INSERT INTO "reigns" VALUES (28,'Morgan','Alienor','1994-01-01','1994-06-18');
INSERT INTO "reigns" VALUES (29,'Wulfric','Eira','1994-06-18','1995-01-07');
INSERT INTO "reigns" VALUES (30,'Timoch','Adelicia','1995-01-07','1995-07-01');
INSERT INTO "reigns" VALUES (31,'Michael','Alessandra Melusine','1995-07-01','1996-01-06');
INSERT INTO "reigns" VALUES (32,'Garick','Talitha','1996-01-06','1996-06-22');
INSERT INTO "reigns" VALUES (33,'Edouard','Eanor','1996-06-22','1997-01-04');
INSERT INTO "reigns" VALUES (34,'Elffin','Vanna','1997-01-04','1997-06-28');
INSERT INTO "reigns" VALUES (35,'Jurgan','Lilliard','1997-06-28','1998-01-03');
INSERT INTO "reigns" VALUES (36,'Matthew','Anna','1998-01-03','1998-06-20');
INSERT INTO "reigns" VALUES (37,'Sven','Thora','1998-06-20','1999-01-09');
INSERT INTO "reigns" VALUES (38,'Prothall','Cecilia','1999-01-09','1999-06-19');
INSERT INTO "reigns" VALUES (39,'Matthew','Anna','1999-06-19','2000-01-08');
INSERT INTO "reigns" VALUES (40,'Elffin','Alessandra Melusine','2000-01-08','2000-06-24');
INSERT INTO "reigns" VALUES (41,'Prothall','Cecilia','2000-06-24','2001-01-06');
INSERT INTO "reigns" VALUES (42,'Peregrine','Alessandra Melusine','2001-01-06','2001-06-30');
INSERT INTO "reigns" VALUES (43,'Elffin','Signy','2001-06-30','2002-01-05');
INSERT INTO "reigns" VALUES (44,'Gerhardt','Aurelia','2002-01-05','2002-06-22');
INSERT INTO "reigns" VALUES (45,'Giles','EzaBella','2002-06-22','2003-01-04');
INSERT INTO "reigns" VALUES (46,'Matthew','Alienor','2003-01-04','2003-06-21');
INSERT INTO "reigns" VALUES (47,'Marcus','Anna','2003-06-21','2004-01-03');
INSERT INTO "reigns" VALUES (48,'Elffin','Signy','2004-01-03','2004-06-19');
INSERT INTO "reigns" VALUES (49,'John','Honor','2004-06-19','2005-01-08');
INSERT INTO "reigns" VALUES (50,'Padraig','Elsa','2005-01-08','2005-06-18');
INSERT INTO "reigns" VALUES (51,'Cadogan','Eufemia','2005-06-18','2006-01-07');
INSERT INTO "reigns" VALUES (52,'Sven','Thora','2006-01-07','2006-06-17');
INSERT INTO "reigns" VALUES (53,'Michael','Moira','2006-06-17','2007-01-06');
INSERT INTO "reigns" VALUES (54,'Maximilian','Margerite','2007-01-06','2007-06-09');
INSERT INTO "reigns" VALUES (55,'Alaric','Nerissa','2007-06-09','2008-01-05');
INSERT INTO "reigns" VALUES (56,'Sven','Jovi','2008-01-05','2008-06-28');
INSERT INTO "reigns" VALUES (57,'Thorvaldr','Fiona','2008-06-28','2009-01-03');
INSERT INTO "reigns" VALUES (58,'Marcus','Cecilia','2009-01-03','2009-06-20');
INSERT INTO "reigns" VALUES (59,'Gerhardt','Judith','2009-06-20','2010-01-09');
INSERT INTO "reigns" VALUES (60,'Thorvaldr','Fiona','2010-01-09','2010-06-19');
INSERT INTO "reigns" VALUES (61,'UlfR','Caoimhe','2010-06-19','2011-01-08');
INSERT INTO "reigns" VALUES (62,'Lief','Morrigan','2011-06-18','2012-01-07');
INSERT INTO "reigns" VALUES (63,'Vitus','Eleanora','2011-01-08','2011-06-18');
INSERT INTO "reigns" VALUES (64,'Sven','Siobhan','2012-01-07','2012-06-16');
INSERT INTO "reigns" VALUES (65,'Paul','Aryanhwy','2012-06-16','2013-01-05');
INSERT INTO "reigns" VALUES (66,'Thorvaldr','Tofa','2013-01-05','2013-06-20');
INSERT INTO "reigns" VALUES (67,'Sven','Siobhan','2013-06-20','2014-01-04');
INSERT INTO "reigns" VALUES (68,'Prothall','Cecilia','2014-01-04','2014-06-21');
INSERT INTO "reigns" VALUES (69,'Lief','Morrigan','2014-06-14','2015-01-03');
INSERT INTO "reigns" VALUES (70,'Makarius','Izabella','2015-01-03','2015-06-27');
INSERT INTO "reigns" VALUES (71,'ThorvaldR','Tomoe','2015-06-27','2016-01-09');
INSERT INTO "reigns" VALUES (72,'Vitus','Isabel','2016-01-09','2016-07-02');
INSERT INTO "reigns" VALUES (73,'Morales','Agnes','2016-07-02','2017-01-07');
INSERT INTO "reigns" VALUES (74,'William','Isabetta','2017-01-07','2017-06-17');
INSERT INTO "reigns" VALUES (75,'Siridean','Jahanara','2017-06-17','2018-01-06');
INSERT INTO "reigns" VALUES (76,'Lief','Morrigan','2018-01-06','2018-06-23');
INSERT INTO "reigns" VALUES (77,'Vitus','Isabel','2018-06-23','2019-01-05');
INSERT INTO "reigns" VALUES (78,'William','Isabetta','2019-01-05','2019-06-22');
INSERT INTO "reigns" VALUES (79,'Vitus','Isabel','2019-06-22','2020-01-04');
INSERT INTO "reigns" VALUES (80,'Æiríkr','Jacquelyna','2020-01-04','');
INSERT INTO "scribes" VALUES (1,'AElfwynn','');
INSERT INTO "scribes" VALUES (2,'Jovi Torstensdottir','');
INSERT INTO "scribes" VALUES (3,'Aelfwynn Leoflaede dohtor','');
INSERT INTO "scribes" VALUES (4,'Genevieve la Flechiere','');
INSERT INTO "scribes" VALUES (5,'Aryanhwy merch Catmael','');
INSERT INTO "scribes" VALUES (6,'Pietari Pentinpoika Uv','');
INSERT INTO "scribes" VALUES (7,'Signý Markúsardóttir','');
INSERT INTO "scribes" VALUES (9,'Dorothea Weberin','');
INSERT INTO "scribes" VALUES (10,'Adorian Piroska','');
INSERT INTO "scribes" VALUES (11,'Signe Scriffuerska','');
INSERT INTO "scribes" VALUES (12,'Ysabella-Maria Vasquez de Granada','');
INSERT INTO "scribes" VALUES (13,'Amal binti Hamid al-Chania','');
INSERT INTO "scribes" VALUES (14,'Cathla inghean ui Cathail','');
INSERT INTO "scribes" VALUES (15,'Hilkka Susinen','');
INSERT INTO "scribes" VALUES (16,'Hawas Gota Krakfot','');
INSERT INTO "scribes" VALUES (17,'Arianrhod o Gymru','');
INSERT INTO "scribes" VALUES (18,'Cassandra Tantifer','');
INSERT INTO "scribes" VALUES (19,'Ylandra Brind Shiobhan','');
INSERT INTO "scribes" VALUES (20,'Oriane dÂ''Avallon','');
INSERT INTO "scribes" VALUES (21,'Saraswati mÃ¡n ikkam','');
INSERT INTO "scribes" VALUES (22,'Maeve of Eplaheimr','');
INSERT INTO "scribes" VALUES (23,'Bridget Greywolf','');
INSERT INTO "scribes" VALUES (24,'Lena the Red','');
INSERT INTO "scribes" VALUES (25,'LÃ¡szlÃ³ from PÃ©cs','');
INSERT INTO "scribes" VALUES (26,'Laszlo from Pecs','');
INSERT INTO "scribes" VALUES (27,'Oriane d''Avallon','');
INSERT INTO "scribes" VALUES (28,'Johannes von Weisswald','');
INSERT INTO "scribes" VALUES (29,'Trinite Ducalon','');
INSERT INTO "scribes" VALUES (30,'Katheryn Hebenstreitz','');
INSERT INTO "scribes" VALUES (31,'Ermingard Hawenthorn','');
INSERT INTO "scribes" VALUES (32,'Estevana d''Orliens','');
INSERT INTO "scribes" VALUES (33,'Lia de Thornegge','');
INSERT INTO "scribes" VALUES (34,'Nordmark Scriptorium','');
INSERT INTO "scribes" VALUES (35,'Torunn Egilsdotter Ask','');
INSERT INTO "scribes" VALUES (36,'Elin Hansdotter Helsings','');
INSERT INTO "scribes" VALUES (37,'Melisende Fitzwalter','');
INSERT INTO "scribes" VALUES (38,'Padraig Gliadrach OÂ''Ceallaigh','');
INSERT INTO "scribes" VALUES (39,'Haakon Pikinokka','');
INSERT INTO "scribes" VALUES (40,'Jolanda de Meyre','');
INSERT INTO "scribes" VALUES (41,'Etienne Fevre de Dion','');
INSERT INTO "scribes" VALUES (42,'Margaretha von RÃ¼ckingen','');
INSERT INTO "scribes" VALUES (43,'Thomas Tanner of Ely','');
INSERT INTO "scribes" VALUES (44,'Ameline de Leeuw','');
INSERT INTO "scribes" VALUES (45,'Cathryn of Chester','');
INSERT INTO "scribes" VALUES (46,'Styringheim scriptorium','');
INSERT INTO "scribes" VALUES (47,'Saraswati man ikkam','');
INSERT INTO "scribes" VALUES (48,'Robert de Canterbury','');
INSERT INTO "scribes" VALUES (49,'Elmeth Carlinous','');
INSERT INTO "scribes" VALUES (50,'unknown','');
INSERT INTO "scribes" VALUES (51,'Margaretha von Rückingen','');
INSERT INTO "scribes" VALUES (52,'Stephanie','');
INSERT INTO "scribes" VALUES (53,'Rhianwen','');
INSERT INTO "scribes" VALUES (54,'Margarite','');
INSERT INTO "scribes" VALUES (55,'Giovanna Lisabetta Ferri','');
INSERT INTO "scribes" VALUES (56,'Giles','');
INSERT INTO "scribes" VALUES (57,'Tamlyn (out of kingdom)','');
INSERT INTO "scribes" VALUES (58,'Angela vom Turmstadt','');
INSERT INTO "scribes" VALUES (59,'Ferri Svensson','');
INSERT INTO "scribes" VALUES (60,'Lyonet de Covenham','');
INSERT INTO "scribes" VALUES (61,'Isengau Scriptorium','');
INSERT INTO "scribes" VALUES (62,'Padraig Gliadrach O''Ceallaigh','');
INSERT INTO "scribes" VALUES (63,'Magdalen Yrjänäntytär','');
INSERT INTO "scribes" VALUES (64,'Ilandra Brin','');
INSERT INTO "scribes" VALUES (65,'Brianna','');
INSERT INTO "scribes" VALUES (66,'Brianna of Arundel','');
INSERT INTO "scribes" VALUES (67,'Alfhild de Foxley','');
INSERT INTO "scribes" VALUES (68,'Ailitha de Ainwyke','');
INSERT INTO "scribes" VALUES (69,'Ailitha de Ainwyk','');
INSERT INTO "scribes" VALUES (70,'Magdalen Yrjänäntytär','');
INSERT INTO "scribes" VALUES (71,'Apollonia','');
INSERT INTO "scribes" VALUES (72,'Honor of Restormel','');
INSERT INTO "scribes" VALUES (73,'Master Jon Blaeston','');
INSERT INTO "scribes" VALUES (74,'Master Jonathan Blaecstan','');
INSERT INTO "scribes" VALUES (75,'Corelia del Castello de Santo Pietro','');
INSERT INTO "scribes" VALUES (76,'Elisande Walters','');
INSERT INTO "scribes" VALUES (77,'Ari Mala','');
INSERT INTO "scribes" VALUES (78,'Nerissa','');
INSERT INTO "scribes" VALUES (79,'SvartulvR','');
INSERT INTO "scribes" VALUES (80,'Emäntä Vallittu + Kerttu Roisko','');
INSERT INTO "scribes" VALUES (81,'Apollonia + Arianhwy merch Catmael','');
INSERT INTO "scribes" VALUES (82,'Saraswati man ikkam + Bridget Greywolf','');
INSERT INTO "scribes" VALUES (83,'Arnfríður Ingvars','');
INSERT INTO "scribes" VALUES (84,'Mikael Rantzow','');
INSERT INTO "scribes" VALUES (85,'Ekaterina Vassilyevna','');
INSERT INTO "scribes" VALUES (86,'Æríkr inn hárfagri','');
INSERT INTO "scribes" VALUES (87,'Åsa Fredriksdotter','');
INSERT INTO "scribes" VALUES (88,'Arianhwy Wen','');
INSERT INTO "scribes" VALUES (89,'Kerttu Roisko','');
INSERT INTO "scribes" VALUES (90,'Kerttu Roisko','');
INSERT INTO "scribes" VALUES (91,'Maerith af Weselax','');
INSERT INTO "scribes" VALUES (92,'Magdalen Yrjänäntytär + Vallittu','');
INSERT INTO "scribes" VALUES (93,'Åsa Baihofer','');
INSERT INTO "scribes" VALUES (94,'Maerith af Weslax','');
INSERT INTO "scribes" VALUES (95,'Wilhelmina','');
INSERT INTO "scribes" VALUES (96,'Magdalen Yrjäntytär','');
INSERT INTO "scribes" VALUES (97,'Izabella del Cacco','');
INSERT INTO "scribes" VALUES (98,'Emilia Gunnarsdotter','');
INSERT INTO "scribes" VALUES (99,'Richard of Salesberie','');
INSERT INTO "scribes" VALUES (100,'Emma Dandelion','');
INSERT INTO "scribes" VALUES (101,'Ava van Allecmere','');
INSERT INTO "scribes" VALUES (102,'Carole Anderson','');
INSERT INTO "scribes" VALUES (103,'Sela de la Rosa','');
INSERT INTO "scribes" VALUES (104,'Master Guntram','');
INSERT INTO "scribes" VALUES (105,'Silwa fran Svaneholm','');
INSERT INTO "scribes" VALUES (106,'Agnes Odygd','');
INSERT INTO "scribes" VALUES (107,'Maarit Pakkala','');
INSERT INTO "scribes" VALUES (108,'Sara Emilia Öberg','');
INSERT INTO "scribes" VALUES (109,'Catelin Munro of Ailsa','');
INSERT INTO "scribes" VALUES (110,'','');
INSERT INTO "scroll_status" VALUES (1,'Awaiting Assignment');
INSERT INTO "scroll_status" VALUES (2,'Assigned');
INSERT INTO "scroll_status" VALUES (3,'Awaiting Signature');
INSERT INTO "scroll_status" VALUES (4,'Completed');
INSERT INTO "scroll_status" VALUES (5,'');
INSERT INTO "events" VALUES (1,'-',NULL,'preexisting data');
INSERT INTO "events" VALUES (1092,'Boot Camp 2022','','DW Calendar');
INSERT INTO "events" VALUES (1095,'Bread War','','DW Calendar');
INSERT INTO "events" VALUES (1100,'Polderfighting','','DW Calendar');
INSERT INTO "events" VALUES (1104,'Coronation 2015','','DW Calendar');
INSERT INTO "events" VALUES (1106,'Nordmark Coronet 2018','','DW Calendar');
INSERT INTO "events" VALUES (1108,'Parasol War','','DW Calendar');
INSERT INTO "events" VALUES (1110,'25y Celebration','','DW Calendar');
INSERT INTO "events" VALUES (1114,'Viking Raid','','DW Calendar');
INSERT INTO "awards" VALUES (9499,4,3623,243,1108,'2018-10-04',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9500,340,3624,18,1100,'1990-04-20',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9501,1,3625,244,1114,'2012-08-04',NULL,NULL,NULL,' \n From the scribe: Apologies for missing the scroll/token information here - in my distraction at the end of court, I failed to retrieve my notes and am working from another copy of the agenda and my memory.','OP crisis management 2022');
INSERT INTO "awards" VALUES (9502,1,3626,243,1095,'2020-02-10',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9503,42,3627,18,1095,'2014-09-13',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9504,40,3628,18,1095,'2006-02-11
',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9505,1,3629,243,1110,'2008-10-03',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9506,1,3630,243,1108,'2016-11-17',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9507,5,3631,244,1104,'2004-09-15',106,NULL,NULL,'Calligraphy and Illumination made by: Agned Odygd \n Scroll not given,','OP crisis management 2022');
INSERT INTO "awards" VALUES (9508,481,3632,130,1092,'2039-01-19',NULL,NULL,NULL,' \n Baron Willian Gifford has decided to keep the scroll and token until he is able to present them personally','OP crisis management 2022');
INSERT INTO "awards" VALUES (9509,260,3633,106,1114,'2022-01-32',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9510,6,3634,167,1106,'2013-06-25',NULL,NULL,NULL,' \n ','OP crisis management 2022');
INSERT INTO "awards" VALUES (9511,297,2418,134,1,'2017-04-09',NULL,NULL,NULL,'','awards received out of kingdom, imported as part of cirsis management 2022');
INSERT INTO "awards" VALUES (9512,503,2418,230,1,'2021-03-27',NULL,NULL,NULL,'','awards received out of kingdom, imported as part of cirsis management 2022');
INSERT INTO "awards" VALUES (9513,31,2418,230,1,'1985-03-25',NULL,NULL,NULL,'','awards received out of kingdom, imported as part of cirsis management 2022');
INSERT INTO "awards" VALUES (9514,505,1545,230,1,'1999-09-09',NULL,NULL,NULL,'','awards received out of kingdom, imported as part of cirsis management 2022');
INSERT INTO "people" VALUES (1557,'Summer','April',3,'Azure, gulles','',NULL);
INSERT INTO "people" VALUES (2489,'Grootten','Tamara',3,'','',NULL);
INSERT INTO "people" VALUES (3226,'Jonsson
','Erik',6,'','','');
INSERT INTO "people" VALUES (3227,'','',6,'','','');
INSERT INTO "people" VALUES (3228,NULL,NULL,6,'','','');
INSERT INTO "people" VALUES (3229,'','',6,'','','');
INSERT INTO "people" VALUES (3230,'','',6,'','','');
INSERT INTO "people" VALUES (3231,'','',6,'','','');
INSERT INTO "people" VALUES (3232,'','',6,'','','');
INSERT INTO "people" VALUES (3233,'','',6,'','','');
INSERT INTO "people" VALUES (3234,'','',6,'','','');
INSERT INTO "people" VALUES (3235,'','',6,'','','');
INSERT INTO "people" VALUES (3236,'','',6,'','','');
INSERT INTO "people" VALUES (3237,'','',6,'','','');
COMMIT;
